apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flower
  template:
    metadata:
      labels:
        component: flower
    spec:
      containers:
        - name: flower
          image: kosamtech/medium-flower:latest
          command: ["/bin/sh", "-c"]
          args: ["/start-flower"]
          ports:
            - containerPort: 5555
          envFrom:
            - configMapRef:
                name: api-server-env