#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

python manage.py collectstatic --no-input
python manage.py migrate

exec /usr/local/bin/gunicorn medium.wsgi --bind 0.0.0.0:8080 --chdir=/app